import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{
          display: 'flex', 
          justifyContent:'center',
          alignItems: 'center',
          fontWeight: '900',
          fontSize: '20px',
          gap: '50px', 
          width: '100%', 
          height: '70px', 
          backgroundColor: 'black',
          borderRadius: '30px 30px 0 0'
        }}>
          <Link href={'/'} style={{color: 'white', textDecoration: 'none'}}>홈</Link>
          <Link href={'/dog'} style={{color: 'white', textDecoration: 'none'}}>강아지</Link>
          <Link href={'/cat'} style={{color: 'white', textDecoration: 'none'}}>고양이</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
